---
- name: Création du dossier
  file:
    path: "{{ app_path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Téléchargement des sources
  unarchive:
    src: "{{ dl_url }}"
    dest: /tmp
    remote_src: true

- name: Copie des sources
  copy:
    src: /tmp/PrestaShop-9.1.4/
    dest: "{{ app_path }}"
    remote_src: true


- name: Attribuer les droits sur l'application
  become: true
  ansible.builtin.file:
    path: "{{ app_path }}"
    owner: "{{ prestashop_user }}"
    group: "{{ prestashop_group }}"
    recurse: true