---
- name: Create directory
  file:
    path: "{{ app_path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Download sources
  unarchive:
    src: "{{ dl_url }}"
    dest: /tmp
    remote_src: true

- name: Copy sources
  copy:
    src: /tmp/PrestaShop-9.1.4/
    dest: "{{ app_path }}"
    remote_src: true


