---
- name: Install dépendances npm thème classic
  shell: npm install
  args:
    chdir: "{{ app_path }}/themes/classic/_dev"
  become: true

- name: Build assets thème classic
  shell: npm run build
  args:
    chdir: "{{ app_path }}/themes/classic/_dev"
  become: true
  
- name: Vérifier si PrestaShop est déjà installé
  stat:
    path: "{{ app_path }}/app/config/parameters.php"
  register: ps_installed

- name: Installation PrestaShop
  shell: >
    php install-dev/index_cli.php
    --domain={{ prestashop_domain }}
    --db_server={{ mysql_server }}
    --db_name={{ bdd_name }}
    --db_user={{ bdd_user }}
    --db_password={{ bdd_password }}
    --db_create=0
    --prefix={{ prestashop_db_prefix }}
    --email={{ prestashop_admin_mail }}
    --password={{ prestashop_admin_password }}
    --theme=classic
  args:
      chdir: "{{ app_path }}"
  when: not ps_installed.stat.exists
