- name: Install Composer dependencies
  community.general.composer:
    command: install
    working_dir: "{{ app_path }}"
  become: true
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"
  register: composer_result
  tags: debug

- name: Log résultat composer install
  debug:
    var: composer_result.stdout_lines
  tags: debug
