---
- name: Build assets thème classic
  command:
    cmd: npm install && npm run build
    chdir: "{{ app_path }}/themes/classic"
  become: true
  become_user: www-data

- name: Installation PrestaShop
  command:
    cmd: >
      php install-dev/index_cli.php
      --domain={{ ansible_host }}
      --db_server={{ mysql_server }}
      --db_name={{ bdd_name }}
      --db_user={{ bdd_user }}
      --db_password={{ bdd_password }}
      --db_create=0
      --prefix={{ prestashop_db_prefix }}
      --email={{ prestashop_admin_mail }}
      --password={{ prestashop_admin_password }}
      --theme=classic
  args:
    chdir: "{{ app_path }}"
    creates: "{{ app_path }}/app/config/parameters.php"