---
- name: Install packages
  become: yes
  apt:
    name:
      - apache2
      - libapache2-mod-php
      - php
      - php-mysql
      - unzip
      - wget
      - composer
    state: present
    update_cache: true

- name: Créer le groupe Prestashop
  become: true
  ansible.builtin.group:
    name: "{{ prestashop_group }}"
    state: present

- name: Créer l'utilisateur Prestashop
  become: true
  ansible.builtin.user:
    name: "{{ prestashop_user }}"
    group: "{{ prestashop_group }}"
    system: true
    create_home: false
    shell: /usr/sbin/nologin
    state: present