---
- name: Install packages
  become: yes
  apt:
    name:
      - apache2
      - libapache2-mod-php
      - php
      - php-mysql
      - unzip
      - wget
      - composer
    state: present
    update_cache: true
