---
- name: Install packages
  become: true
  apt:
    name:
      - apache2
      - libapache2-mod-php
      - php
      - php-mysql
      - php-cli
      - php-common
      - php-curl
      - php-xml
      - php-gd
      - php-intl
      - php-mbstring
      - php-zip
      - php-bcmath
      - unzip
      - wget
      - composer
    state: present
    update_cache: true

