---
- hosts: bdd_group
  become: true
  roles:
    - mysql

- hosts: app_group
  become: true
  roles:
    - prestashop

- name: Résumé du déploiement
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Affichage du résumé
      debug:
        msg: |
           Déploiement DST terminé           
           Base de données  : {{ hostvars['bdd']['ansible_host'] }}
           Application      : https://{{ prestashop_domain }}
          