---
- name: Create database
  ansible.mysql.mysql_db:
    name: "{{ bdd_name }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ root_password }}"

- name: Log base de données
  debug:
    msg: "Base de données '{{ bdd_name }}' prête."