---
- name: Grant privileges
  become: yes
  shell: |
    mysql -u root --password='{{ root_password }}' --socket=/run/mysqld/mysqld.sock <<'EOF'
    CREATE USER IF NOT EXISTS '{{ bdd_user }}'@'%' IDENTIFIED WITH caching_sha2_password BY '{{ bdd_password }}';
    ALTER USER '{{ bdd_user }}'@'%' IDENTIFIED WITH caching_sha2_password BY '{{ bdd_password }}';
    GRANT ALL PRIVILEGES ON `{{ bdd_name }}`.* TO '{{ bdd_user }}'@'%';
    FLUSH PRIVILEGES;
    EOF
  no_log: true
  changed_when: false
