---
- name: Create database
  ansible.mysql.mysql_db:
    name: "{{ bdd_name }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
    login_user: root

- name: Définir le mot de passe root MySQL
  become: yes
  shell: |
    mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '';"
    mysql -u root -e "FLUSH PRIVILEGES;"
  changed_when: false
