---
- name: Grant privileges
  ansible.mysql.mysql_user:
    name: "{{ bdd_user }}"
    password: "{{ bdd_password }}"
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock
    priv: "{{ bdd_name }}.*:ALL"
    state: present
