---
- name: Grant privileges
  ansible.mysql.mysql_user:
    name: "{{ bdd_user }}"
    password: "{{ bdd_password }}"
    host: "{{ authorized_ips }}"
    priv: "{{ bdd_name }}.*:ALL"
    state: present
