- name: Définir le mot de passe root MySQL
  become: yes
  shell: |
    mysql -u root  root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '{{ root_password }}';"
    mysql -u root  root -e "FLUSH PRIVILEGES;"
  changed_when: false
