- name: Définir le mot de passe root MySQL
  become: yes
  shell: |
    if ! mysql -u root --password='{{ root_password }}' -e "SELECT 1;" 2>/dev/null; then
      mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '{{ root_password }}';"
      mysql -u root -e "FLUSH PRIVILEGES;"
    fi
  changed_when: false
