---
- name: Check if MySQL is already installed
  command: mysqladmin --version
  register: mysql_installed
  failed_when: false
  changed_when: false

- name: Install MySQL
  become: yes
  apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present
    update_cache: false
  when: mysql_installed.rc != 0


- name: Listen on all interfaces
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: restart mysql

