---
- name: Install MySQL
  become: yes
  apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present
    update_cache: false
  changed_when: false  # Évite de marquer la tâche comme "changed" à chaque exécution
  ignore_errors: yes   # Au cas où la commande échoue (ex: si MySQL est déjà sécurisé)


- name: Listen on all interfaces
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: restart mysql

