#SPDX-License-Identifier: MIT-0
---
- import_tasks: install.yaml
- import_tasks: networking.yaml
- import_tasks: security.yaml
- import_tasks: create_bdd.yaml
- import_tasks: create_user.yaml
- import_tasks: configration.yaml
